# This is a jenkins file with declarative syntax approach
pipeline {
    agent any  // Runs the pipeline on any available agent

    environment {
        // Define environment variables here
        MY_VAR = 'some_value'
    }
    tools{
        maven 'mvn 3.9.5'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout source code from version control
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // Build the project
                echo 'Building the project...'
                sh './build.sh'  // Executes a shell script
            }
        }

        stage('Test') {
            steps {
                // Run tests
                echo 'Running tests...'
                sh './test.sh'
            }
        }

        stage('Deploy') {
            steps {
                // Deploy the application
                echo 'Deploying the application...'
                sh './deploy.sh'
            }
        }
    }

    post {
        success {
            // Actions to perform if the pipeline succeeds
            echo 'Pipeline succeeded!'
        }
        failure {
            // Actions to perform if the pipeline fails
            echo 'Pipeline failed.'
        }
        always {
            // Actions to perform regardless of success or failure
            echo 'Cleaning up...'
        }
    }
}
