# This is a jenkins file with declarative syntax approach
pipepline{
     stages{
          stage{
               steps{
          
               }
          }  
    }
     stages{
      stage{
        steps{
          
        }
      }
    }
  stages{
      stage{
        steps{
          
        }
      }
  
    }
}
